# Generated by Django 3.2.5 on 2024-01-10 15:24

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('name', models.CharField(max_length=100, verbose_name='Укажите имя')),
                ('surname', models.CharField(max_length=100, verbose_name='Укажите фамилию')),
                ('phone_number', models.CharField(default='+996', max_length=13, verbose_name='Укажите номер телефона')),
                ('date_of_birth', models.DateField(verbose_name='Ваша дата рождения')),
                ('gender', models.CharField(choices=[(1, 'M'), (2, 'Ж'), (3, 'Неизвестно')], max_length=10, verbose_name='Ваш пол')),
                ('hobby', models.CharField(max_length=100, verbose_name='Укажите хобби')),
                ('device', models.CharField(choices=[('ПК', 'ПК'), ('Мобильное устройство', 'Мобильное устройство')], max_length=100, verbose_name='Укажите ваше основное устройство')),
                ('social_media', models.CharField(max_length=100, verbose_name='Укажите никнейм в соц сетях')),
                ('marital_status', models.CharField(max_length=100, verbose_name='Укажите семейное положение')),
                ('city', models.CharField(max_length=100, verbose_name='Укажите ваш город проживания')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
