# Generated by Django 3.2.5 on 2024-01-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('MALE', 'M'), ('FEMALE', 'Ж'), ('UNDEFINED', '-')], max_length=10, verbose_name='Ваш пол'),
        ),
    ]
