# Generated by Django 5.0 on 2023-12-17 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Укажите название видео')),
                ('image', models.ImageField(upload_to='youtube_videos/', verbose_name='Укажите превью видео')),
                ('description', models.TextField(verbose_name='Укажите описание видео')),
                ('price', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5), django.core.validators.MaxValueValidator(20)], verbose_name='Укажите стоимость видео')),
                ('genre', models.CharField(choices=[('Презентационные видеоролики', 'Презентационные видеоролики'), ('Демонстрационные ролики', 'Демонстрационные ролики'), ('Испытательные ролики', 'Испытательные ролики'), ('Сравнительные ролики', 'Сравнительные ролики'), ('Ситуационные ролики', 'Ситуационные ролики')], max_length=100, verbose_name='Укажите жанр видеоролика')),
                ('author', models.TextField(verbose_name='Автор видео')),
                ('trailer', models.URLField(default='https://www.youtube.com/', verbose_name='Укажите ссылку на видео (Youtube)')),
            ],
        ),
    ]
