# Generated by Django 5.0 on 2023-12-13 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=40, verbose_name='Book Name')),
                ('book_description', models.TextField(verbose_name='Book Description')),
                ('book_image', models.ImageField(upload_to='', verbose_name='Book Image')),
                ('book_price', models.DecimalField(decimal_places=3, max_digits=150, verbose_name='Book Price')),
                ('book_author', models.CharField(max_length=40, verbose_name='Book Author')),
                ('book_upload_at', models.DateTimeField(auto_now_add=True, verbose_name='Book Upload At')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
            },
        ),
    ]
