# Generated by Django 5.0 on 2023-12-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='book_price',
            field=models.DecimalField(decimal_places=15, max_digits=150, verbose_name='Book Price'),
        ),
    ]
