# Generated by Django 5.0 on 2023-12-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_booklist_book_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='book_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Book Price'),
        ),
    ]
